### ISSUE TITLE
Request for this to be merged into the official faust repository.

### ISSUE THREAD

**Issue by mbylstra** [FlatIO/faudiostream#1]
The Faust source code is now officially hosted at https://github.com/grame-cncm/faust, which means you can request for this to be merged into master. I'd do it myself with my own fork, but you should get the credit for the work! The big advantage is that docker builds can be kept up to date with the latest official faust version.

I think a Dockerfile is a valuable addition to Faust, and I think the Faust team can be convinced too.

**Comment by gierschv** [comment]
Thanks for your message, we made this fork on Github when the project was still on Sourceforge I think, I will check to send this PR and remove this repository.

Vincent

**Comment by gierschv** [comment]
Done, merged on 27/11/2016
